shftgroup/gisst

gisst-server/migrations/20230425185923_create_base_tables.down.sql, gisst-server/migrations/20230425185923_create_base_tables.up.sql, gisst-server/src/bin/gisst-server-cli/args.rs, gisst-server/src/bin/gisst-server-cli/main.rs, gisst-server/src/models.rs
Addressing some of the generic calls in the CLI api. Also implemented creator and replay functions and adjusted some of the model API (like removing DBLinked).
=> Generics cli 0004

frontend-web/src/main.ts, gisst-server/migrations/20230425185923_create_base_tables.down.sql, gisst-server/migrations/20230425185923_create_base_tables.up.sql, gisst-server/src/bin/gisst-server-cli/main.rs, gisst-server/src/bin/gisst-server/src/templates.rs, gisst-server/src/lib.rs, gisst-server/src/model_enums.rs, gisst-server/src/models.rs
Changing the framework to environment, all changes should be made. Still an issue with replay and state file delete but that will be resolved with another pull request. 
This address #1 .
=> 1 move instance framework to environment framework

frontend-elec/index.html, frontend-elec/src/renderer.ts
=> Add fields to type instance, state, replay for elec

backend/gisst-cli/src/args.rs, backend/gisst-cli/src/main.rs, backend/gisst/src/models.rs
Fixes last (?) remaining issue of file db transition
=> Fix insertion of replays and tidy up create replay function in CLI

backend/Cargo.toml, backend/config/default.toml, backend/gisst/src/storage.rs, backend/ingest/src/main.rs, backend/rdb-sys/build.rs, backend/rdb-sys/src/lib.rs
MVP for ingest from RDB data.  I discovered that many games have multiple entries in the RDB (with different checksums) and the "right" thing to do is probably to merge the data for each of those entries based on ROM name or something.  Anyway, for now it's a quick way to load in a bunch of ROMs so I'll get it running on the server.
It might not run properly on other computers until a patch I submitted to retroarch lands.
=> Ingest rdb

backend/config/default.toml, backend/gisst-server/src/main.rs, backend/gisst-server/src/routes.rs, backend/gisst-server/src/server.rs, backend/gisst-server/src/serverconfig.rs, backend/gisst-server/src/templates/instance_all_listing.liquid, backend/gisst-server/src/templates/instance_listing.liquid, backend/gisst/src/models.rs, gisst-player-ui/package-lock.json, gisst-player-ui/package.json
this will address #47 and adds two new listing pages for instances to click into the browser.
=> 47 endpoints for listing of clickable instances and embedding state replay save data into frontend api calls

backend/clear_data.sh, backend/gisst-server/src/routes.rs, backend/gisst-server/src/server.rs, backend/gisst-server/src/templates/instance_all_listing.liquid, backend/gisst-server/src/templates/instance_listing.liquid, frontend/gisst-player-ui/src/html/templates.html, frontend/gisst-player-ui/src/ts/main.ts, frontend/gisst-player-ui/src/ts/models.ts, frontend/gisst-player-ui/src/ts/template_consts.ts
adding in basic styling for /instances and /instance/{id}/all pages
=> 71 add work information to pages

.gitignore, backend/Cargo.lock, backend/gisst-server/src/routes.rs, backend/gisst-server/src/server.rs, backend/gisst-server/src/templates/instance_all_listing.liquid, backend/gisst/Cargo.toml, backend/gisst/src/models.rs, backend/migrations/20230926221258_alter_creator_table.down.sql, frontend/frontend-web/src/ra.ts, frontend/frontend-web/src/types.d.ts, frontend/frontend-web/src/v86.ts, frontend/gisst-player-ui/src/ts/main.ts, frontend/gisst-player-ui/src/ts/models.ts
Fixed replay and state upload for RA and v86. Fixed cross-site issue with v86 embed code.
=> 79 replay upload broken on screenshot

frontend/gisst-player-ui/src/html/templates.html, frontend/gisst-player-ui/src/scss/styles.scss, frontend/gisst-player-ui/src/ts/main.ts
=> 88 enable editing replay metadata

backend/gisst-server/src/auth.rs, backend/gisst-server/src/server.rs, backend/gisst-server/src/serverconfig.rs
=> Add base_url config parameter for auth redirects

frontend/frontend-embed/index.html, frontend/frontend-embed/public/media/canvas-ra.svg, frontend/frontend-embed/public/media/canvas-v86.svg, frontend/frontend-embed/public/media/canvas.svg, frontend/frontend-embed/src/canvas.svg, frontend/frontend-embed/src/main.ts, frontend/frontend-web/public/media/canvas-ra.svg, frontend/frontend-web/public/media/canvas-v86.svg, frontend/frontend-web/public/media/canvas.svg, frontend/frontend-web/src/main.ts, frontend/frontend-web/src/v86.ts, frontend/gisst-player-ui/src/html/templates.html, simple/embed_one.html
This seems to work for both frontend-web and frontend-embed.
=> Force resize canvas to fit container

backend/gisst-server/Cargo.toml, backend/gisst-server/src/error.rs, backend/gisst-server/src/server.rs, backend/gisst-server/src/templates/index.html, backend/gisst-server/src/templates/single_citation_page.html, frontend/frontend-embed/src/main.ts, frontend/frontend-embed/src/style.css
Added in citation resolution page for text/html requests to citation /data url.
=> 148 simple citation resolution page

frontend/frontend-embed/src/v86.ts, frontend/frontend-web/src/v86.ts
This just captures on any click, it may be better instead to capture on pressing a particular UI button?
=> capture mouse on click in v86

backend/gisst-cli/src/cliconfig.rs, backend/gisst/src/error.rs, backend/gisst/src/fslist.rs
This makes listing work for the ELO image.
=> fix nested dir listing by skipping . and .. always

backend/examples/data/v86/freedos722-root.json, backend/examples/load_examples.sh, backend/gisst-cli/src/args.rs, backend/gisst-cli/src/main.rs, backend/gisst-server/src/error.rs, backend/gisst-server/src/routes.rs, backend/gisst-server/src/templates/instance_all_listing.html, backend/gisst/Cargo.toml, backend/gisst/src/error.rs, backend/gisst/src/lib.rs, backend/gisst/src/v86clone.rs
Add a basic clone button for v86 states
=> V86 clone button

backend/gisst-server/src/tus.rs, backend/gisst/src/storage.rs, frontend/embedv86/src/main.ts
this caused files to be put in e.g. `storage/.../filename/filename`
=> fix the wrong dest path being used in storage handler

backend/gisst/src/models.rs, backend/migrations/20241029192820_make_file_dest_path_a_complete_path.up.sql, frontend/frontend-web/src/ra.ts, frontend/frontend-web/src/v86.ts, frontend/gisst-player-ui/src/ts/db.ts, frontend/gisst-player-ui/src/ts/main.ts, frontend/gisst-player-ui/src/ts/models.ts
=> Reupload state/replay with new desc/ID

backend/gisst-cli/src/main.rs
I had a condition flipped :facepalm:
=> Fix patch file command in gisst-cli

.github/workflows/rust.yml, backend/Cargo.lock, backend/gisst/Cargo.toml, backend/gisst/src/error.rs, backend/gisst/src/fslist.rs
For cross-platform purposes, we'll replace libmagic with treemagic.
=> Add treemagic

.github/workflows/deploy.yml, .github/workflows/node.js.yml, .github/workflows/rust.yml, backend/load_examples.sh
Run load_examples.sh and check the number of loaded things
=> Make CI a bit more robust around changes to database-related stuff

.github/workflows/rust.yml, backend/config/default.toml, backend/gisst-server/src/templates/instance_all_listing.html, backend/gisst/src/v86clone.rs, backend/load_examples.sh, frontend/embedv86/src/main.ts, frontend/embedv86/types/main.d.ts, frontend/frontend-web/src/v86.ts
- Clone button URL was wrong
- Clone state file path was computed wrongly
- V86 ignored memory_size parameter and used 64MB always
- Updated example state/replay to use correct memory size
- Changed default loglevel for gisst crate in server
=> Fix clone and wrong memory settings under v86

dist-update.sh
RA merged my fetchfs changes so we don’t need my fork anymore.
=> Switch back to mainline retroarch

backend/gisst-server/src/main.rs
This fixes a hang in tokio/axum
=> Install otlp as a batch exporter

backend/Cargo.lock, backend/config/default.toml, backend/gisst-server/Cargo.toml, backend/gisst-server/src/auth.rs, backend/gisst-server/src/main.rs, backend/gisst-server/src/routes.rs, backend/gisst-server/src/server.rs, backend/gisst/src/fslist.rs, backend/gisst/src/storage.rs
also add a few more examples of tracing
=> Fix tracing for new otel API, have a stdout fallback

backend/gisst-server/src/routes/creator.rs, backend/gisst-server/src/routes/instance.rs, backend/meili/init_indices.sh
This matches the old behavior better and is just useful.
=> small meili tweak to sort saves/states/replays by created_on desc

.github/workflows/rust.yml, backend/gisst-cli/src/args.rs, backend/gisst-cli/src/main.rs, backend/gisst-server/src/templates/player.html, backend/gisst/src/search.rs, backend/ingest/src/main.rs, backend/load_examples.sh
- Fixes a bug I missed with the player template (using "body" instead of "content")
- Adds a gisst-cli command to add a work and instance at once
=> Add work instance command

dist-update.sh
This fixes dist-update for more recent RA builds.
=> Add HAVE_RWEBAUDIO=0 flag to RA compilation

backend/gisst-server/src/templates/creator_all_listing.html, frontend/server-ui/src/ts/main.ts
Changed server to not show user emails to other users.
=> Changed user name to user full name to remove emails from public view
